# Generated by Django 5.0 on 2023-12-31 00:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('favorite_name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=100)),
                ('product_store_id', models.IntegerField()),
                ('product_img_url', models.CharField()),
                ('product_price', models.FloatField()),
                ('product_sale_price', models.FloatField(default=0.0)),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frugal.favorite')),
            ],
        ),
    ]
