# Generated by Django 5.0 on 2023-12-31 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frugal', '0002_rename_created_date_favorite_date_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='date_updated',
            new_name='date_created',
        ),
    ]
