# Generated by Django 5.0 on 2024-01-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frugal', '0004_alter_product_product_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='favorite_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_img_url',
            new_name='imgage_url',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_sale_price',
            new_name='sale_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_store_id',
            new_name='store_id',
        ),
        migrations.AddField(
            model_name='favorite',
            name='average_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='price_history',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
