# Generated by Django 5.0 on 2024-01-01 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frugal', '0005_rename_favorite_name_favorite_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_history',
        ),
    ]
