# Generated by Django 5.0 on 2024-01-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frugal', '0006_remove_product_price_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='store_id',
            field=models.CharField(),
        ),
    ]
