# Generated by Django 5.0 on 2024-01-03 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frugal', '0007_alter_product_store_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 3, 20, 43, 32, 483872, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 3, 20, 43, 32, 483501, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 3, 20, 43, 32, 505654, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 3, 20, 43, 32, 505663, tzinfo=datetime.timezone.utc)),
        ),
    ]
