# Generated by Django 5.0 on 2024-01-04 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frugal', '0008_favorite_date_updated_alter_favorite_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 21, 49, 10, 29938, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 21, 49, 10, 30145, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 21, 49, 10, 41468, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 21, 49, 10, 41479, tzinfo=datetime.timezone.utc)),
        ),
    ]
