# Generated by Django 5.0 on 2024-01-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frugal', '0009_alter_favorite_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='date_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='date_updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_updated',
            field=models.DateTimeField(),
        ),
    ]
