# Generated by Django 5.0 on 2024-02-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frugal', '0010_alter_favorite_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
